---
# Windows Jenkins agent setup

- name: Configure Windows Jenkins agent
  hosts: windows
  gather_facts: true

  roles:
    - role: java
      tags: [java]
    - role: docker
      tags: [docker]
    - role: nodejs
      tags: [nodejs, python, git]
    - role: jenkins-agent
      tags: [jenkins-agent]
